import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './styles/globals.scss';
import { ReactNode } from 'react';

const inter = Inter({
	variable: '--font-inter',
});

export const metadata: Metadata = {
	title: {
		template: '%s | Taskflow',
		default: 'Taskflow',
	},
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: ReactNode;
}>) {
	return (
		<html lang='ru'>
			<body className={`${inter.variable}`}>{children}</body>
		</html>
	);
}
